#config/solr_wrapper_test.yml
# version: 6.1.0
port: 8985
version: 6.6.0
download_dir: /var/tmp
instance_dir: /var/tmp/solr-test
collection:
    persist: false
    dir: solr/config
    name: hydra-test
